### ISSUE TITLE
期待加入本地音视频文件推流功能

### ISSUE THREAD

**Issue by Rogueyang** [EasyDarwin/EasyPusher_Android#6]
如题，不知贵公司有没有计划开发此功能

**Comment by babosa** [comment]
EasyDarwin是由全国多地的开发者自发组织的一个开源开发团队，EasyPusher**没有**关于将本地文件进行直播推流的开发计划，这个功能不是什么技术难点，只是一个文件解析的过程，所以，您那边可以参考其他视频文件解析的代码，自行完成；
