### ISSUE TITLE
安卓集成后so怎么处理的

### ISSUE THREAD

**Issue by jp1017** [EasyDarwin/EasyPusher_Android#7]
现在直接copy libeasypusher.so到项目, 也用到了EasyPusher类, 里面的几个native 方法, 导致找不到,

除了修改包名还需要怎么处理呢?自己编译?

**Comment by jp1017** [comment]
自己集成一个aar库, 搞掂!

**Comment by babosa** [comment]
哈哈，自力更生，自给自足了，辛苦辛苦

**Comment by douya40** [comment]
我改成aar,jni调用报错
